-- 순서에 구애받지 않는 강제 초기화 방식 (대체안)
DROP TABLE t_comment CASCADE CONSTRAINTS;
DROP TABLE t_portfolio CASCADE CONSTRAINTS;
DROP TABLE t_stock_price CASCADE CONSTRAINTS;
DROP TABLE t_post CASCADE CONSTRAINTS;
DROP TABLE t_history CASCADE CONSTRAINTS;
DROP TABLE t_stock CASCADE CONSTRAINTS;
DROP TABLE t_category CASCADE CONSTRAINTS;
DROP TABLE t_cash CASCADE CONSTRAINTS;
DROP TABLE t_user CASCADE CONSTRAINTS;
DROP TABLE t_sector CASCADE CONSTRAINTS;

DROP SEQUENCE seq_t_comment;
DROP SEQUENCE seq_t_history;
DROP SEQUENCE seq_t_post;
DROP SEQUENCE seq_t_user;
